
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://127.0.0.1:3306/ai_interviewer?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: DataSourceHikariCP           # 连接池的名字
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
    data:
      redis:
        host: 127.0.0.1
        port: 6380
        password: 123456
        database: 0
long:
  frontend:
    url: http://127.0.0.1:5500

# MinIO配置
minio:
  endpoint: http://127.0.0.1:9000   # MinIO服务地址
  fileHost: http://10.7.136.2:9000 # 文件地址（使用内网IP）
  bucketName: ai-interviewer
  accessKey: admin
  secretKey: admin123456

zhiPuAi:
  API_KEY: 7c392b36a9164eb7a5cbe9896ce0a0b3.Br4FGriy08I6xKBI
